Allow user to specify the init values for each component of the tuple
BlueQuartzSoftware/SIMPL pull request #399
Opened 2020-05-06 15:17 UTC by imikejackson

Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>

2020-05-06 17:26 UTC, JDuffeyBQ requested changes

2020-05-06 17:26 UTC, JDuffeyBQ commented on Source/SIMPLib/CoreFilters/CreateDataArray.cpp
> +CDA_CREATE_CONVERTOR(uint8_t, toUInt)
All the non class functions can be put into an anonymous namespace.

2020-05-06 17:26 UTC, JDuffeyBQ commented on Source/SIMPLib/CoreFilters/CreateDataArray.cpp
> +#define CDA_RB "]"
```suggestion
constexpr char CDA_SEP = ';';
constexpr char CDA_LB = '[';
constexpr char CDA_RB = ']';
```
Change to constexpr char variables.

2020-05-06 17:26 UTC, JDuffeyBQ commented on Source/SIMPLib/CoreFilters/CreateDataArray.cpp
> +  };
```
#define CDA_CREATE_CONVERTOR(type, func)                                                                                                                                                               \
  template <>                                                                                                                                                                                          \
  struct convert_from<type>                                                                                                                                                                            \
  {                                                                                                                                                                                                    \
    static type convert(const QString& input)                                                                                                                                                          \
    {                                                                                                                                                                                                  \
      bool ok = false;                                                                                                                                                                                 \
      type value = static_cast<type>(input.func(&ok));                                                                                                                                                    \
      if(!ok)                                                                                                                                                                                          \
      {                                                                                                                                                                                                \
        return 0;                                                                                                                                                                                      \
      }                                                                                                                                                                                                \
      return value;                                                                                                                                                                                    \
    }                                                                                                                                                                                                  \
  };

template <class T>
struct convert_from
{
};

CDA_CREATE_CONVERTOR(uint8_t, toUInt)
CDA_CREATE_CONVERTOR(int8_t, toInt)
CDA_CREATE_CONVERTOR(uint16_t, toUShort)
CDA_CREATE_CONVERTOR(int16_t, toShort)
CDA_CREATE_CONVERTOR(uint32_t, toUInt)
CDA_CREATE_CONVERTOR(int32_t, toInt)
CDA_CREATE_CONVERTOR(uint64_t, toULongLong)
CDA_CREATE_CONVERTOR(int64_t, toLongLong)
CDA_CREATE_CONVERTOR(bool, toInt)
```

Using template specializations in the macro removes the need for the conversion template parameter in createInitVector(). The convert function can also be made static.

2020-05-06 17:26 UTC, JDuffeyBQ commented on Source/SIMPLib/CoreFilters/CreateDataArray.cpp
> +void CreateDataArray::checkInitialization(QString dataArrayName)
Putting in a list of components fails for float and double.

2020-05-06 17:26 UTC, JDuffeyBQ commented on Source/SIMPLib/CoreFilters/CreateDataArray.cpp
>      bool ok;
Should be initialized.

2020-05-06 17:26 UTC, JDuffeyBQ commented on Source/SIMPLib/CoreFilters/CreateDataArray.cpp
> +        std::ignore = token.toDouble(&ok);
We should check the conversion with the actual type. For example if you enter -1 for an unsigned type, it the Qt functions fail to convert it resulting in 0, but it is a silent error during dataCheck().

2020-05-06 21:34 UTC, imikejackson commented
All the requested changes have been made.

2020-05-07 00:07 UTC, JDuffeyBQ requested changes

2020-05-07 00:07 UTC, JDuffeyBQ commented on Source/SIMPLib/CoreFilters/CreateDataArray.cpp
> +        conversionResult = convert.convert(tokens[0]);
```suggestion
        conversionResult = convert_from<T>::convert(tokens[0]);
```
Call statically here and in the other spots. Can remove local variables afterwards.

2020-05-07 16:42 UTC, merged