Change AttributeMatrix/IGeometry Types Enumeration to std::vector from QVector
BlueQuartzSoftware/SIMPL pull request #416
Opened 2021-02-11 13:55 UTC by imikejackson

Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>

2021-02-11 13:57 UTC, imikejackson commented
DREAM3DCI passed on all platforms
https://dev.azure.com/BlueQuartzSoftware/DREAM3D/_build/results?buildId=426&view=results

2021-02-11 17:57 UTC, JDuffeyBQ requested changes
It may be a good idea to implement our own contains function since we use it a lot.

```
namespace SIMPL
{
template <class Iterator, class T>
constexpr bool contains(Iterator first, Iterator last, const T& value)
{
  // Can't use std::find in the implemention for constexpr until C++20

  for(; first != last; ++first)
  {
    if(*first == value)
    {
      return true;
    }
  }

  return false;
}
} // namespace SIMPL
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SIMPLib/DataContainers/AttributeMatrix.cpp
> +          if(amTypes.empty() || std::find(amTypes.begin(), amTypes.end(), static_cast<AttributeMatrix::Type>(amTypeTmp)) != amTypes.end()
```suggestion
          if(amTypes.empty() || std::find(amTypes.cbegin(), amTypes.cend(), static_cast<AttributeMatrix::Type>(amTypeTmp)) != amTypes.cend()
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SIMPLib/DataContainers/DataContainer.cpp
> +        auto result = std::find(std::begin(geomTypes), std::end(geomTypes), static_cast<IGeometry::Type>(geometryType));
```suggestion
        auto result = std::find(geomTypes.cbegin(), geomTypes.cend(), static_cast<IGeometry::Type>(geometryType));
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SIMPLib/DataContainers/DataContainer.cpp
> +        if(geomTypes.empty() || result != std::end(geomTypes))
```suggestion
        if(geomTypes.empty() || result != geomTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/FilterParameterWidgets/FilterParameterWidgetUtils.hpp
> +        if(std::find(std::begin(geomTypes), std::end(geomTypes), static_cast<IGeometry::Type>(geomType)) == std::end(geomTypes))
```suggestion
        if(std::find(geomTypes.cbegin(), geomTypes.cend(), static_cast<IGeometry::Type>(geomType)) == geomTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/FilterParameterWidgets/FilterParameterWidgetUtils.hpp
> +        // if(!geomTypes.contains(geomType))
```suggestion
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/FilterParameterWidgets/FilterParameterWidgetUtils.hpp
> +          auto result = std::find(std::begin(defVec), std::end(defVec), static_cast<AttributeMatrix::Type>(am->getType()));
```suggestion
          auto result = std::find(defVec.cbegin(), defVec.cend(), static_cast<AttributeMatrix::Type>(am->getType()));
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/FilterParameterWidgets/FilterParameterWidgetUtils.hpp
> +          if(nullptr != am.get() && !defVec.empty() && result == std::end(defVec))
```suggestion
          if(nullptr != am.get() && !defVec.empty() && result == defVec.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/FilterParameterWidgets/LinkedDataContainerSelectionWidget.cpp
> +    if(!geomTypes.empty() && result == std::end(geomTypes) && result1 == std::end(geomTypes))
```suggestion
    auto result = std::find(geomTypes.cbegin(), geomTypes.cend(), static_cast<IGeometry::Type>(geomType));
    auto result1 = std::find(geomTypes.cbegin(), geomTypes.cend(), IGeometry::Type::Any);

    if(!geomTypes.empty() && result == geomTypes.cend() && result1 == geomTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/Widgets/DataArrayPathSelectionWidget.cpp
> +    if(result1 == std::end(reqs.dcGeometryTypes))
```suggestion
    auto result1 = std::find(reqs.dcGeometryTypes.cbegin(), reqs.dcGeometryTypes.cend(), IGeometry::Type::Unknown);
    if(result1 == reqs.dcGeometryTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/Widgets/DataArrayPathSelectionWidget.cpp
> +      if(result == std::end(reqs.dcGeometryTypes) && result2 == std::end(reqs.dcGeometryTypes))
```suggestion
      auto result = std::find(reqs.dcGeometryTypes.cbegin(), reqs.dcGeometryTypes.cend(), geom->getGeometryType());
      auto result2 = std::find(reqs.dcGeometryTypes.cbegin(), reqs.dcGeometryTypes.cend(), IGeometry::Type::Any);

      if(result == reqs.dcGeometryTypes.cend() && result2 == reqs.dcGeometryTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/Widgets/DataArrayPathSelectionWidget.cpp
> +    if(result1 == std::end(reqs.dcGeometryTypes))
```suggestion
    auto result1 = std::find(reqs.dcGeometryTypes.cbegin(), reqs.dcGeometryTypes.cend(), IGeometry::Type::Unknown);
    if(result1 == reqs.dcGeometryTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/Widgets/DataArrayPathSelectionWidget.cpp
> +      if(result == std::end(reqs.dcGeometryTypes) && result2 == std::end(reqs.dcGeometryTypes))
```suggestion
      auto result = std::find(reqs.dcGeometryTypes.cbegin(), reqs.dcGeometryTypes.cend(), geom->getGeometryType());
      auto result2 = std::find(reqs.dcGeometryTypes.cbegin(), reqs.dcGeometryTypes.cend(), IGeometry::Type::Any);

      if(result == reqs.dcGeometryTypes.cend() && result2 == reqs.dcGeometryTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/Widgets/DataArrayPathSelectionWidget.cpp
> +  if(result == std::end(reqs.amTypes))
```suggestion
  auto result = std::find(reqs.amTypes.cbegin(), reqs.amTypes.cend(), AttributeMatrix::Type::Unknown);

  if(result == reqs.amTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/Widgets/DataArrayPathSelectionWidget.cpp
> +    if(!reqs.amTypes.empty() && result1 == std::end(reqs.amTypes) && result2 == std::end(reqs.amTypes))
```suggestion
    auto result1 = std::find(reqs.amTypes.cbegin(), reqs.amTypes.cend(), am->getType());
    auto result2 = std::find(reqs.amTypes.cbegin(), reqs.amTypes.cend(), AttributeMatrix::Type::Any);
    if(!reqs.amTypes.empty() && result1 == reqs.amTypes.cend() && result2 == reqs.amTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/Widgets/DataArrayPathSelectionWidget.cpp
> +    if(result == std::end(reqs.dcGeometryTypes))
```suggestion
    auto result = std::find(reqs.dcGeometryTypes.cbegin(), reqs.dcGeometryTypes.cend(), IGeometry::Type::Unknown);

    if(result == reqs.dcGeometryTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/Widgets/DataArrayPathSelectionWidget.cpp
> +      if(result1 == std::end(reqs.dcGeometryTypes) && result2 == std::end(reqs.dcGeometryTypes))
```suggestion
      auto result1 = std::find(reqs.dcGeometryTypes.cbegin(), reqs.dcGeometryTypes.cend(), geom->getGeometryType());
      auto result2 = std::find(reqs.dcGeometryTypes.cbegin(), reqs.dcGeometryTypes.cend(), IGeometry::Type::Any);
      if(result1 == reqs.dcGeometryTypes.cend() && result2 == reqs.dcGeometryTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/Widgets/DataArrayPathSelectionWidget.cpp
> +  if(result == std::end(reqs.amTypes))
```suggestion
  auto result = std::find(reqs.amTypes.cbegin(), reqs.amTypes.cend(), AttributeMatrix::Type::Unknown);

  if(result == reqs.amTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/Widgets/DataArrayPathSelectionWidget.cpp
> +    if(!reqs.amTypes.empty() && result1 == std::end(reqs.amTypes) && result2 == std::end(reqs.amTypes))
```suggestion
    auto result1 = std::find(reqs.amTypes.cbegin(), reqs.amTypes.cend(), am->getType());
    auto result2 = std::find(reqs.amTypes.cbegin(), reqs.amTypes.cend(), AttributeMatrix::Type::Any);
    if(!reqs.amTypes.empty() && result1 == reqs.amTypes.cend() && result2 == reqs.amTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/Widgets/DataArrayPathSelectionWidget.cpp
> +  if(result3 == std::end(reqs.daTypes))
```suggestion
  auto result3 = std::find(reqs.daTypes.cbegin(), reqs.daTypes.cend(), da->getTypeAsString());
  if(result3 == reqs.daTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/Widgets/ImportASCIIDataWizard/DataFormatPage.cpp
> +    if(!geomTypes.empty() && result == std::end(geomTypes) && result1 == std::end(geomTypes))
```suggestion
    auto result = std::find(geomTypes.cbegin(), geomTypes.cend(), static_cast<IGeometry::Type>(geomType));
    auto result1 = std::find(geomTypes.cbegin(), geomTypes.cend(), IGeometry::Type::Any);

    if(!geomTypes.empty() && result == geomTypes.cend() && result1 == geomTypes.cend())
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/Widgets/ImportASCIIDataWizard/DataFormatPage.cpp
> +      bool amValidType = !amTypes.empty() && result2 == std::end(amTypes);
```suggestion
      auto result2 = std::find(amTypes.cbegin(), amTypes.cend(), am->getType());
      bool amValidType = !amTypes.empty() && result2 == amTypes.cend();
```

2021-02-11 17:57 UTC, JDuffeyBQ commented on Source/SVWidgetsLib/Widgets/ImportASCIIDataWizard/DataFormatPage.cpp
> +    if(!geomTypes.empty() && result == std::end(geomTypes) && result1 == std::end(geomTypes))
```suggestion
    auto result = std::find(geomTypes.cbegin(), geomTypes.cend(), static_cast<IGeometry::Type>(geomType));
    auto result1 = std::find(geomTypes.cbegin(), geomTypes.cend(), IGeometry::Type::Any);

    if(!geomTypes.empty() && result == geomTypes.cend() && result1 == geomTypes.cend())
```

2021-02-12 19:48 UTC, JDuffeyBQ approved these changes

2021-02-13 02:29 UTC, merged